# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c1f2127a2281a81388bb76fed447a8d7f09ff59adf6b20f2309a6c9d6573be9b18022660acae6d4f2589077f02339eb1f22b2357d169a399f58604403bfe5e4

test:
  secret_key_base: 30b034786d40a37a443a4c988ad62f9227dabadf196b98bf3419fcf65fd1fae05239dbb9c78b30c2191b35a80439415224159df7e33deaa6265529492dc07d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
